services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - back-app/.env
    environment:
      POSTGRES_DB: lokinho         # Banco de dados a ser criado
      POSTGRES_USER: postgres      # Usuário do Postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-deploy-volume:/var/lib/postgresql/data

  node:
    container_name: back-app
    build: ./back-app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/lokinho"
    env_file:
      - back-app/.env
    volumes:
      - back-deploy-volume:/src/usr/LokinhoRifas/dist/uploads

  web:
    container_name: next
    build: ./my-app
    ports: 
      - 8080:3000
    depends_on:
      - node
    env_file:
      - my-app/.env.local

volumes:
  postgres-deploy-volume:
  back-deploy-volume:
