services:
  node:
    container_name: back-app
    build: ./back-app
    restart: always
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: "postgresql://lokinhodb:thiagoco@172.17.0.1:5432/lokinho"
    env_file:
      - back-app/.env
    volumes:
      - back-deploy-volume:/src/usr/LokinhoRifas/dist/uploads

  web:
    container_name: next
    build: ./my-app
    ports:
      - 3000:3000
    depends_on:
      - node
    env_file:
      - my-app/.env.local

volumes:
  back-deploy-volume:
